# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3acc68f5d21623140a64986dc81a983cef88822449ecb762facd53ed9e78dfdfeddbbab58d2b50b82a93259999d0ba89a811e9491c3c69aadf8b51a89ab6eaca

test:
  secret_key_base: 302555081c5f0b5b2c39c0ee9e22111558ab5f637320147f78492e124fb71fa4fa3a326e198ba36726db3dc824f8b535d7bab9f812284535c79e87fce107d95c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
